# Generated by Django 5.0 on 2023-12-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_scrollmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollmodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
